// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/chord/check": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chord"
                ],
                "summary": "determine chord and tune",
                "parameters": [
                    {
                        "description": "Note numbers and key info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ChordCheckRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ChordCheckResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Chord": {
            "type": "object",
            "properties": {
                "chordRootNote": {
                    "type": "string"
                },
                "chordToneArray": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ChordTone"
                    }
                },
                "chordType": {
                    "type": "string"
                }
            }
        },
        "model.ChordCheckResponse": {
            "type": "object",
            "properties": {
                "chordWithInScaleArray": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Chord"
                    }
                },
                "chordWithoutScaleArray": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Chord"
                    }
                }
            }
        },
        "model.ChordTone": {
            "type": "object",
            "properties": {
                "degree": {
                    "$ref": "#/definitions/model.Degree"
                },
                "letterName": {
                    "type": "string"
                }
            }
        },
        "model.Degree": {
            "type": "object",
            "properties": {
                "centsFromEqualToJust": {
                    "type": "number",
                    "example": -14
                },
                "degreeName": {
                    "type": "string",
                    "example": "長3度"
                }
            }
        },
        "models.ChordCheckRequest": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string",
                    "example": "C"
                },
                "noteNumberArray": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        60,
                        64,
                        67
                    ]
                },
                "scaleType": {
                    "type": "string",
                    "example": "Major"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
